### ISSUE TITLE
Error: Alignment with name = "AL_DENV_1" not found

### ISSUE THREAD

**Issue by gvaleman** [giffordlabcvr/Dengue-GLUE#1]
Hello,

I have been trying to run GLUE to determine dengue virus lineages, but I've encountered some issues. I successfully installed GLUE natively and created a "dengue project" without any problems.

However, when following the instructions in the GitHub repository on how to genotypify, I encountered the following error:

```
Error: Alignment with name = "AL_DENV_1" not found
```

I understand that the necessary files to run Dengue GLUE are included in the Dengue GLUE repository on GitHub, but I noticed that the "alignment" folder is missing. The main GLUE documentation suggests this folder.

Could you please guide me on the potential causes of this error and how I can resolve it?

Below are the command lines I executed and the error I received:

```
GLUE Version 1.1.113 Copyright (C) 2015-2020 The University of Glasgow This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions. For details see GNU Affero General Public License v3: http://www.gnu.org/licenses/

Mode path: / 
GLUE> project dengue 
OK 
Mode path: /project/dengue 
GLUE> module denv2MaxLikelihoodGenotyper genotype file -f '/home/my_dir/dengue/all_consensus_DENV_1.fasta' 
Error: Alignment with name = "AL_DENV_1" not found
Mode path: /project/dengue
```

Thank you for your help.

**Comment by robjgiff** [comment]
Hi, and thanks for your message. 

I am currently updating the genotyping tools in line with recent updates to the proposed nomeclature. Following review of the associated manuscript (now in press at PLoS Biology) some quite significant changes were made to the nomenclature by the lead authors.

I am making my updates on a separate repository branch, but yesterday I prematurely merged my development branch into the main branch. I think this underlies the issue you encountered. Apologies for the confusion.

I have since restored the main branch, I rebuilt the project and tested the command as follows:

```
Mode path: /project/dengue
GLUE> module denv2MaxLikelihoodGenotyper genotype file -f sources/fasta-testseqs-denv2/EU482760.1_2005.fas 
+=================+====================+====================+=========================+=========================+============================+
|    queryName    | serotypeFinalClade | genotypeFinalClade | major_lineageFinalClade | minor_lineageFinalClade | minor_sublineageFinalClade |
+=================+====================+====================+=========================+=========================+============================+
| EU482760.1_2005 | AL_DENV_2          | AL_DENV_2III       | AL_DENV_2III_D          | AL_DENV_2III_D1         | AL_DENV_2III_D1.3          |
+=================+====================+====================+=========================+=========================+============================+
```
The test sequences are included in the most recent version of the repo, so this command should work for you.

Please note, however, that the lineage assignments currently reflect the version of the nomenclature described in the preprint, not the more recent updates.

I advise to rebuild the project* and retry the command. If you still encounter an error please let me know.

*Note - as an alternative to  running the build process you can also install from the database dumpfile included in the repo using the following commands, adjusting to match your MySQL installation:

```
   gunzip dengue_glue.sql.gz
   
   /usr/local/mysql/bin/mysql  --user=gluetools --password=glue12345 GLUE_TOOLS < dengue_glue.sql
```

**Comment by gvaleman** [comment]
Hi,

This is very helpful for me. Thank you very much for the clear explanation and for this incredible work.
